"""Resilient parser for tool calls generated by Qwen 2.5 models."""

import json
import re
import ast
from typing import Any, Dict, List, Optional, Tuple


def _try_parse_json_dict(text: str) -> Optional[Dict[str, Any]]:
    """Attempt to parse a string into a JSON dictionary, with common cleanup."""
    text = text.strip()
    if not text:
        return None
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    # Try cleaning trailing commas or markdown backticks
    cleaned = re.sub(r",\s*([\]}])", r"\1", text)
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    # Try python literal eval if json failed (e.g. single quotes)
    try:
        data = ast.literal_eval(text)
        if isinstance(data, dict):
            return data
    except Exception:
        pass

    return None


def parse_tool_calls(
    response_data: Dict[str, Any],
    valid_tool_names: Optional[List[str]] = None,
) -> List[Dict[str, Any]]:
    """
    Extract structured tool calls from an Ollama response dictionary or text.
    Returns list of dicts: [{"name": str, "arguments": dict}]
    """
    tool_calls: List[Dict[str, Any]] = []
    valid_set = set(valid_tool_names) if valid_tool_names else None

    # 1. Check native Ollama / OpenAI tool_calls
    native_calls = response_data.get("tool_calls", [])
    if native_calls:
        for call in native_calls:
            func = call.get("function", {})
            name = func.get("name", "")
            args = func.get("arguments", {})

            if isinstance(args, str):
                parsed_args = _try_parse_json_dict(args)
                args = parsed_args if parsed_args is not None else {}

            if name:
                if valid_set is None or name in valid_set:
                    tool_calls.append({"name": name, "arguments": args if isinstance(args, dict) else {}})

        if tool_calls:
            return tool_calls

    # 2. Check message content for text-embedded tool calls
    content = response_data.get("content", "")
    if not content:
        return tool_calls

    # Pattern A: <tool_call>{"name": "...", "arguments": ...}</tool_call>
    xml_matches = re.findall(r"<tool_call>\s*(.*?)\s*</tool_call>", content, re.DOTALL)
    for match in xml_matches:
        d = _try_parse_json_dict(match)
        if d:
            name = d.get("name") or d.get("tool") or d.get("function")
            args = d.get("arguments") or d.get("parameters") or {k: v for k, v in d.items() if k not in ("name", "tool", "function")}
            if name and (valid_set is None or name in valid_set):
                tool_calls.append({"name": name, "arguments": args if isinstance(args, dict) else {}})

    if tool_calls:
        return tool_calls

    # Pattern B: ```json codeblocks containing {"name": "...", "arguments": ...}
    json_blocks = re.findall(r"```(?:json)?\s*(\{.*?\})\s*```", content, re.DOTALL)
    for block in json_blocks:
        d = _try_parse_json_dict(block)
        if d:
            name = d.get("name") or d.get("tool") or d.get("function")
            args = d.get("arguments") or d.get("parameters")
            if args is None:
                args = {k: v for k, v in d.items() if k not in ("name", "tool", "function")}
            if name and (valid_set is None or name in valid_set):
                tool_calls.append({"name": name, "arguments": args if isinstance(args, dict) else {}})

    if tool_calls:
        return tool_calls

    # Pattern C: Direct function call regex: tool_name(param1="val", ...) or tool_name param1="val" ...
    if valid_set:
        for tool_name in valid_set:
            if tool_name == "run_command":
                continue
            # Match tool_name(...) or tool_name param="..."
            pattern = rf"\b{re.escape(tool_name)}(?:\s*\((.*?)\)|\s+([a-zA-Z_]+\s*=.*))"
            for match in re.finditer(pattern, content, re.DOTALL):
                arg_str = (match.group(1) or match.group(2) or "").strip()
                parsed_args = {}
                if arg_str:
                    kv_pairs = re.findall(r'(\w+)\s*=\s*(?:"([^"]*)"|\'([^\']*)\'|([^\s,]+))', arg_str)
                    for key, v1, v2, v3 in kv_pairs:
                        val = v1 or v2 or v3
                        parsed_args[key] = val

                    # Fallback single argument if no key=value
                    if not parsed_args and (tool_name in ("read_file", "list_directory", "create_directory", "delete_file")):
                        cleaned_val = arg_str.strip(' "\'()')
                        parsed_args["path"] = cleaned_val

                if parsed_args or tool_name == "list_directory":
                    tool_calls.append({"name": tool_name, "arguments": parsed_args})

    if tool_calls:
        return tool_calls

    # Pattern D: Fallback bash codeblocks ```bash command ``` -> run_command
    if valid_set is None or "run_command" in valid_set:
        bash_blocks = re.findall(r"```(?:bash|sh|shell|zsh)\s*(.*?)\s*```", content, re.DOTALL)
        for block in bash_blocks:
            cleaned_cmd = block.strip()
            # Ignore echo or comments only or commands starting with registered tools
            if cleaned_cmd and not cleaned_cmd.startswith("#"):
                first_word = cleaned_cmd.split()[0] if cleaned_cmd.split() else ""
                if valid_set and first_word in valid_set and first_word != "run_command":
                    continue
                tool_calls.append({"name": "run_command", "arguments": {"command": cleaned_cmd}})

    # Pattern E: Line starting with $ command or pacman/yay/sudo command
    if not tool_calls and (valid_set is None or "run_command" in valid_set):
        for line in content.splitlines():
            line_str = line.strip()
            if line_str.startswith("$ "):
                cmd = line_str[2:].strip()
                if cmd:
                    first_word = cmd.split()[0] if cmd.split() else ""
                    if valid_set and first_word in valid_set and first_word != "run_command":
                        continue
                    tool_calls.append({"name": "run_command", "arguments": {"command": cmd}})
            elif any(line_str.startswith(prefix) for prefix in ("sudo pacman", "pacman -", "flatpak install", "pip install", "python3 ", "npm ", "pytest")):
                tool_calls.append({"name": "run_command", "arguments": {"command": line_str}})

    return tool_calls
